spring:
  main:
    banner-mode: off
  thymeleaf:
    enabled: true
  datasource:
    username: leo
    password: 34FynbDbg!!@@##
    url: jdbc:postgresql://localhost/INTERNETSHOP
    hikari:
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  liquibase:
    user: leo
    password: 34FynbDbg!!@@##
    url: jdbc:postgresql://localhost/INTERNETSHOP
    change-log: classpath:db.changelog/db.changelog-master.xml
server:
  port: 8081
